#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════════
# Cloudflare Tunnel — Local Config Setup
# ═══════════════════════════════════════════════════════════════════════════
# Generates cloudflared/config.yml and copies credentials.json from
# ~/.cloudflared/ based on .env variables.
#
# Usage:
#   ./scripts/setup-tunnel.sh
#   # or
#   make tunnel-setup
# ═══════════════════════════════════════════════════════════════════════════

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$ROOT_DIR/.env"
CREDENTIALS_DIR="$HOME/.cloudflared"

# ─── Load .env ─────────────────────────────────────────────────────────────
if [ -f "$ENV_FILE" ]; then
    # Export variables from .env, ignoring comments and empty lines
    while IFS='=' read -r key value; do
        # Skip comments and empty lines
        case "$key" in
            ''|\#*) continue ;;
        esac
        # Remove surrounding quotes from value if present
        value="$(echo "$value" | sed -e 's/^"//' -e 's/"$//' -e "s/^'//" -e "s/'$//")"
        export "$key=$value"
    done < "$ENV_FILE"
fi

# ─── Validate required variables ──────────────────────────────────────────
if [ -z "$CLOUDFLARE_TUNNEL_ID" ]; then
    echo "❌ CLOUDFLARE_TUNNEL_ID not set in .env"
    echo ""
    echo "   Setup:"
    echo "   1. cloudflared tunnel login"
    echo "   2. cloudflared tunnel create garamatic"
    echo "   3. echo 'CLOUDFLARE_TUNNEL_ID=<tunnel-id>' >> .env"
    echo "   4. echo 'CLOUDFLARE_DOMAIN=your-domain.com' >> .env"
    exit 1
fi

if [ -z "$CLOUDFLARE_DOMAIN" ]; then
    echo "❌ CLOUDFLARE_DOMAIN not set in .env"
    exit 1
fi

# ─── Copy credentials file ────────────────────────────────────────────────
CREDENTIALS_SOURCE="$CREDENTIALS_DIR/$CLOUDFLARE_TUNNEL_ID.json"
CREDENTIALS_DEST="$ROOT_DIR/cloudflared/credentials.json"

if [ ! -f "$CREDENTIALS_SOURCE" ]; then
    echo "❌ Credentials file not found: $CREDENTIALS_SOURCE"
    echo ""
    echo "   Your tunnel was created but the credentials file is missing."
    echo "   Try one of:"
    echo "   • cloudflared tunnel create garamatic  (creates a new one)"
    echo "   • cloudflared tunnel list              (shows existing tunnels)"
    exit 1
fi

mkdir -p "$ROOT_DIR/cloudflared"
cp "$CREDENTIALS_SOURCE" "$CREDENTIALS_DEST"
chmod 644 "$CREDENTIALS_DEST"

# ─── Generate config.yml ───────────────────────────────────────────────────
CONFIG_FILE="$ROOT_DIR/cloudflared/config.yml"

cat > "$CONFIG_FILE" <<EOF
# ═══════════════════════════════════════════════════════════════════════════
# Auto-generated by scripts/setup-tunnel.sh
# Do not edit manually — edit .env and re-run make tunnel-setup
# ═══════════════════════════════════════════════════════════════════════════

tunnel: ${CLOUDFLARE_TUNNEL_ID}
credentials-file: /etc/cloudflared/credentials.json

ingress:
  # ─── Frontends ─────────────────────────────────────────────
  - hostname: portal.${CLOUDFLARE_DOMAIN}
    service: http://portal:80
    originRequest:
      noTLSVerify: true

  - hostname: web.${CLOUDFLARE_DOMAIN}
    service: http://garamatic-web:8080
    originRequest:
      noTLSVerify: true

  - hostname: masala.${CLOUDFLARE_DOMAIN}
    service: http://masala-web:8080
    originRequest:
      noTLSVerify: true

  - hostname: showcase.${CLOUDFLARE_DOMAIN}
    service: http://showcase:80
    originRequest:
      noTLSVerify: true

  # ─── APIs ──────────────────────────────────────────────────
  - hostname: api.${CLOUDFLARE_DOMAIN}
    service: http://gatekeeper-api:8080
    originRequest:
      noTLSVerify: true

  - hostname: tickets.${CLOUDFLARE_DOMAIN}
    service: http://ticket-masala:8080
    originRequest:
      noTLSVerify: true

  - hostname: agentic.${CLOUDFLARE_DOMAIN}
    service: http://agentic-service:3001
    originRequest:
      noTLSVerify: true

  - hostname: odoo-bridge.${CLOUDFLARE_DOMAIN}
    service: http://odoo-integration:8080
    originRequest:
      noTLSVerify: true

  # ─── Infrastructure ────────────────────────────────────────
  - hostname: mailhog.${CLOUDFLARE_DOMAIN}
    service: http://mailhog:8025
    originRequest:
      noTLSVerify: true

  - hostname: rabbitmq.${CLOUDFLARE_DOMAIN}
    service: http://rabbitmq:15672
    originRequest:
      noTLSVerify: true

  - hostname: odoo.${CLOUDFLARE_DOMAIN}
    service: http://odoo:8069
    originRequest:
      noTLSVerify: true

  # ─── LLM / Ollama ────────────────────────────────────────
  - hostname: ollama.${CLOUDFLARE_DOMAIN}
    service: http://llama:8080
    originRequest:
      noTLSVerify: true

  # ─── MCP Server ───────────────────────────────────────────
  - hostname: mcp.${CLOUDFLARE_DOMAIN}
    service: http://agentic-mcp:3001
    originRequest:
      noTLSVerify: true

  # ─── Monitoring / Observability ───────────────────────────
  - hostname: monitor.${CLOUDFLARE_DOMAIN}
    service: http://grafana:3000
    originRequest:
      noTLSVerify: true

  - hostname: prometheus.${CLOUDFLARE_DOMAIN}
    service: http://prometheus:9090
    originRequest:
      noTLSVerify: true

  - hostname: loki.${CLOUDFLARE_DOMAIN}
    service: http://loki:3100
    originRequest:
      noTLSVerify: true

  - hostname: tempo.${CLOUDFLARE_DOMAIN}
    service: http://tempo:3200
    originRequest:
      noTLSVerify: true

  # ─── Catch-all ─────────────────────────────────────────────
  - service: http_status:404
EOF

# ─── Success ──────────────────────────────────────────────────────────────
echo "✅ Tunnel configuration generated"
echo "   Tunnel ID:   ${CLOUDFLARE_TUNNEL_ID}"
echo "   Domain:      ${CLOUDFLARE_DOMAIN}"
echo "   Credentials: ${CREDENTIALS_DEST}"
echo "   Config:      ${CONFIG_FILE}"
echo ""
echo "   Next steps:"
echo "   1. (Optional) Edit cloudflared/config.yml to customize hostnames"
echo "   2. Run: make tunnel-up"
